# Generated by Django 3.2.5 on 2022-07-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('US', 'USA'), ('IN', 'India'), ('NZ', 'New Zealand'), ('CN', 'China'), ('CL', 'Chile')], max_length=100),
        ),
    ]
